### ISSUE TITLE
Preferences -> Maven -> Source Lookup fails to open with latest Mars releases

### ISSUE THREAD

**Issue by Wnt** [ifedorenko/com.ifedorenko.m2e.sourcelookup#11]
Like someone commented on Eclipse market place:

After install this plugin, expand: window -- preferences -- Maven, click Source Lookup, will prompt "The currently displayed page contains invalid values"

![screenshot from 2015-06-17 14 35 13](https://cloud.githubusercontent.com/assets/886091/8205988/2cafcb5e-14fe-11e5-902f-1c53cab72a92.png)

Also, if the Dynamic Source Lookup Launch Extension is selected, Elipse will prompt
```
"An internal error occurred during: "Launching tempdash-ui jetty..run".
org.eclipse.m2e.internal.launch.MavenLaunchUtils.getBundleEntry(Lorg/osgi/framework/Bundle;Ljava/lang/String;)Ljava/lang/String;"
```
when trying to start the debug configuration. Unselecting the Dynamic Source Lookup Launch Extension makes the debug configuration run as expected.

**Comment by ifedorenko** [comment]
Where did you install sourcelookup from? Mars compat problem was fixed by 4be126d87c8717191e206c91e0daaf73c8034617 in two+ months ago.

**Comment by Wnt** [comment]
I installed from your updatesite http://ifedorenko.github.com/m2e-extras/
These are the plugin versions it contains according to my Eclipse:
```
m2e dynamic source code lookup	1.1.0.201409160038
Maven Development Tools	0.3.0.201410040035
```
Have you not released fixed builds of the plugins yet?

**Comment by ifedorenko** [comment]
I didn't have time to maintain http://ifedorenko.github.com/m2e-extras/ and need to decide what to do about it. 

In the mean time, you can install sourcelookup, maven dev tools and everything else you need to work on maven core and maven plugins from https://repository.takari.io/content/sites/m2e.extras/takari-team/0.1.0/N/LATEST/. This is what I use, so when it breaks, I fix it fast ;-)

I'll keep this issue open as a reminder to do something about m2e-extras and eclipse marketplace entries.

**Comment by Wnt** [comment]
Might be a good idea to remove the mars compatibility from the market place plugin or update the update site to point to a maintained one:
https://marketplace.eclipse.org/content/m2e-dynamic-sources-lookup

Not sure how else one could find that repository.takari.io/... url if not involved more with m2e development.

**Comment by ifedorenko** [comment]
I've updated Maven Dev Tools to include Sourcelookup support and updated both m2e-extras and eclipse marketplace. I also requested sourcelookup marketplace entry to be permanently deleted. This should solve the problem for the time being.
