### ISSUE TITLE
Can't install on Eclipse Luna J2EE (4.4.2)

### ISSUE THREAD

**Issue by jens-meiss** [ifedorenko/com.ifedorenko.m2e.sourcelookup#13]
It seem's that, since version 1.1.0.201506181114, the plugin can't be installed via the update site on eclipse 4.4

Updatesite: http://ifedorenko.github.com/m2e-extras/
Eclipse Version: http://eclipse.mirror.triple-it.nl/technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-linux-gtk-x86_64.tar.gz

Here the error message while installing:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Maven Development Tools 0.3.0.201506181201 (com.ifedorenko.m2e.mavendev.feature.feature.group 0.3.0.201506181201)
  Missing requirement: Maven Development Tools 0.3.0.201506181116 (com.ifedorenko.m2e.mavendev 0.3.0.201506181116) requires 'bundle org.eclipse.m2e.launching [1.6.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Maven Development Tools 0.3.0.201506181201 (com.ifedorenko.m2e.mavendev.feature.feature.group 0.3.0.201506181201)
    To: com.ifedorenko.m2e.mavendev [0.3.0.201506181116]

Eclipse 4.4 use version 1.5.1 of org.eclipse.m2e.launching.

**Comment by ifedorenko** [comment]
You need to use Eclipse 4.5/Mars and M2E 1.6 to use recent versions of Maven Dev Tools.

**Comment by jens-meiss** [comment]
can't you provide a version for eclipse 4.4? because eclipse 4.5 is still full of bugs and useless for me ...

isn't it possible to put two different version in the repository, one for 4.4 and one for 4.5?

**Comment by ifedorenko** [comment]
I don't have time/interest to maintain compatibility with multiple eclipse versions.

You can use older Maven Dev Tools version if you want, however. https://github.com/ifedorenko/m2e-extras is git repository and you can checkout any version you like. (sorry, don't remember when I introduce hard Mars dependency)

**Comment by jens-meiss** [comment]
ok thx for the info
