### ISSUE TITLE
Add contextual shortcut, i.e.: org.eclipse.debug.ui.launchShortcuts

### ISSUE THREAD

**Issue by bitstrings** [ifedorenko/com.ifedorenko.m2e.sourcelookup#21]
Might be great to have "Maven Junit" contextual shortcut.

**Comment by ifedorenko** [comment]
What is "Maven JUnit", can you elaborate?

For the record, jdt "JUnit Test" and m2e "Maven JUnit Test" are supposed to use advanced sourcelookup already.

**Comment by bitstrings** [comment]
I use the source lookup from

https://repository.takari.io/content/sites/m2e.extras/takari-team/0.1.0/N/LATEST

But Advanced doesn't work in Oxygen (Debug as).

So I use the "Maven JUnit Launcher" for mavendev (plugin) instead and it works good.

However, there is no contextual shortcut like JUnit or TestNG when right-clicking on a Test (Debug as).

**Comment by ifedorenko** [comment]
When did you last update your takari-team/0.1.0/N/LATEST version? It is supposed to come with newer sourcelookup [1] and should support jdt "JUnit Test"  launch configuration out of the box. You do need to choose "Advanced Eclipse JUnit Launcher" either in workspace preferences or individual launch configurations [2]. 

As for TestNG, I don't use it myself and cannot comment, sorry.

[1] https://repository.takari.io/content/sites/m2e.extras/sourcelookup/1.2.0/N/LATEST/
[2] https://screencast.com/t/oMGXUNxVX

**Comment by bitstrings** [comment]
No no I'm not expecting support for TestNG, that was just an example.

I've tested this yesterday.

However i see a new url with v1.2.0.  I will test that.

It's nice to have all these maven tools but to find them is not trivial.

**Comment by bitstrings** [comment]
The URL you gave me https://repository.takari.io/content/sites/m2e.extras/sourcelookup/1.2.0/N/LATEST/
gets me the same version I am using which doesn't work with Oxygen.

**Comment by bitstrings** [comment]
This is what I get

![image](https://cloud.githubusercontent.com/assets/911165/26652831/2be6bad0-461f-11e7-98bf-385264f06f8d.png)


It used to work.

**Comment by bitstrings** [comment]
v1.2.0.201704030110 seems to work...
