### ISSUE TITLE
Is there a tag or release created for "1.2.0.201704030045"?

### ISSUE THREAD

**Issue by tonyfalabella** [ifedorenko/com.ifedorenko.m2e.sourcelookup#22]
Is there a tag or release created for "1.2.0.201704030045"?  I work at a company that blocks the update sites but allows zip or gz downloads so ideally I'd like to manually download the archive and install it into Eclipse Neon manually.

**Comment by ifedorenko** [comment]
pushed the tag

**Comment by tonyfalabella** [comment]
Got it.  Thank you.
