### ISSUE TITLE
Still, in 2017 :(

### ISSUE THREAD

**Issue by GroupThink** [ifedorenko/com.ifedorenko.m2e.sourcelookup#23]
Illegal character in path at index 20: file:/C:/Users/Group Think/eclipse/jee-oxygen/eclipse/../../../.p2/pool/plugins/com.ifedorenko.m2e.sourcelookup_1.1.0.201506181114/com.ifedorenko.m2e.sourcelookup.javaagent.jar

(from Eclipse Jee Oxygen - space in filename)

**Comment by ifedorenko** [comment]
dup of #12
