### ISSUE TITLE
unable to start project project

### ISSUE THREAD

**Issue by bobbylough** [ifedorenko/com.ifedorenko.m2e.sourcelookup#3]
getting the following error :

Error opening zip file or JAR manifest missing : C:\Program
Error occurred during initialization of VM
agent library failed to init: instrument

I was able to get this running on a previous machine but on my current workspace.

I am running Kepler with 
m2e dynamic source code lookup	1.1.0.201309291737	
Eclipse.org m2e - Maven Integration for Eclipse 1.4.0.2013.0601-0317

**Comment by ifedorenko** [comment]
Same as issue #12
